# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # pip deps
  - package-ecosystem: pip
    target-branch: "master"
    schedule:
      interval: weekly
    directory: /
    commit-message:
      prefix: "deps"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry*"
      patch:
        update-types:
          - patch

  # github deps
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    directory: "/"
