{{- if and .Values.storage.enabled .Values.storage.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  labels:
    app: {{ template "map-proxy.name" . }}
    component: map-proxy
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.storageSize }}
{{- end }}
