{{- if and (.Values.rasterCommon.authentication.opa.enabled) (not .Values.nginx.enabledOpala) }}
{{- $chartName := include "mapproxy.name" . -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-opa
data:
  policy.rego: |-
{{ tpl (.Files.Get "config/policy.rego") . | b64enc | indent 4 }}
{{- end }}
